name: Run Tests

on:
  push:
    branches: ['dev-ts']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm ci

    - name: Run Tests with Coverage
      run: npm test -- --coverage

    - name: Upload Coverage Results
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage/